alows monitor selection using fzf

diff --git a/bin/bin/swp b/bin/bin/swp
--- a/bin/bin/swp
+++ b/bin/bin/swp
@@ -1,43 +1,66 @@
 #!/usr/bin/env bash
 
-MONITORS=`hyprctl monitors | grep Monitor | awk '{print $2}'`
-
-if [ -z "$1" ];
-then
-  echo "No image provided, Restoring from cache ..."
-  WALLPP=$(cat "$HOME/.cache/wallpp")
-  echo $WALLPP
-
-  if [ -z "$WALLPP" ]; then
-    echo "Cache is empty. Please provide an image path"
-    exit 1
-  fi
-
-  wal -i "$WALLPP" -n --cols16 dual
-
-  hyprctl hyprpaper preload "$WALLPP"
-  for i in $monitors; do
-    hyprctl hyprpaper wallpaper "$i, $WALLPP";
-  done;
-else
-  WALLPP=$(realpath "$1")
-  echo $WALLPP
-
-  if [ ! -f "$WALLPP" ]; then
-    echo "Error: File $WALLPP does not exist"
-    exit 1
-  fi
-
-  echo "Generating Colourscheme"
-  wal -i $WALLPP -n --cols16 dual
-
-  echo $WALLPP > $HOME/.cache/wallpp
-
-  sed -i "s|path = .*|path = $WALLPP|" "$HOME/.config/hypr/hyprpaper.conf"
-
-  echo $MONITORS
-
-  for i in $MONITORS; do
-    hyprctl hyprpaper wallpaper "$i, $WALLPP";
-  done;
+CACHE_DIR="$XDG_CACHE_HOME/wallpp_cache"
+if [ ! -z "$CACHE_DIR" ]; then
+  mkdir -p $CACHE_DIR
 fi
+
+IMG_PATH=$1
+TARGET_MONITOR=$2
+
+get_all_monitors() {
+  hyprctl monitors -j | jq -r '.[] | .name'
+}
+
+apply_wall() {
+  awww img "$WALLPP" \
+    --outputs "$mon" \
+    --resize fit \
+    --transition-type wave
+}
+
+
+# Restore Mode: loop through all active monitors and restore their specific wallpapers
+if [ -z "$IMG_PATH" ]; then
+  echo "Restoring wallpapers from cache"
+  get_all_monitors | while read -r mon; do
+    if [ -f "$CACHE_DIR/$mon" ]; then
+      WALLPP=$(cat "$CACHE_DIR/$mon")
+      apply_wall
+    fi
+  done
+  exit 0
+fi
+
+# New Image Mode
+WALLPP=$(realpath "$IMG_PATH")
+[ ! -f "$WALLPP" ] && echo "Error: File $WALLPP does not exist" && exit 1
+
+# monitor selection
+if [ "$TARGET_MONITOR" == "--select" ]; then
+  # manual selection with fzf
+  TARGET_MONITOR=$(get_all_monitors | fzf --prompt="Select Monitor: " --reverse --border)
+  [ -z "$TARGET_MONITOR" ] && echo "Selection cancelled." && exit 0
+  SELECTED_MONITORS=("$TARGET_MONITOR")
+elif [ -n "$TARGET_MONITOR" ]; then
+  # specific monitor provided as $2
+  if ! get_all_monitors | grep -q "^$TARGET_MONITOR$"; then
+    echo "Error: Monitor '$TARGET_MONITOR' not found."
+    exit 1
+  fi
+  SELECTED_MONITORS=("$TARGET_MONITOR")
+else
+  # No monitor specified: Get all active monitors
+  mapfile -t SELECTED_MONITORS < <(get_all_monitors)
+fi
+
+# Apply to all selected monitors
+for mon in "${SELECTED_MONITORS[@]}"; do
+  echo "Setting wallpaper for $mon"
+  echo "$WALLPP" > "$CACHE_DIR/$mon"
+  apply_wall
+done
+
+# Generate Pywal16 Colors
+wal -i "$WALLPP" -n
+echo "Wallpaper updated for: ${SELECTED_MONITORS[*]}"
